package com.comp490.studybuddy.note;

import android.content.Intent;
import android.view.ActionMode;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.widget.ImageButton;

import com.comp490.studybuddy.R;

/* Generated by VideoBuilder onLongClick of a Video ImageButton. Provides a 
 * menu of options, including deletion of view (not the file) and also 
 * plays video fullscreen with VideoViewerActivity
 */
public class VideoMenu implements ActionMode.Callback {
	private NoteActivity noteActivity;
	private VideoBuilder videoBuilder;
	//private static final String LOG_TAG = "Video Menu Callback";
	ImageButton video;

	// Video Contextual Action Mode

	public VideoMenu(NoteActivity noteActivity, VideoBuilder videoBuilder) {
		this.noteActivity = noteActivity;
		this.videoBuilder = videoBuilder;
		video = (ImageButton) noteActivity.findViewById(videoBuilder.getEntry().getViewID());
	}

	@Override
	public boolean onCreateActionMode(ActionMode mode, Menu menu) {
		MenuInflater inflater = mode.getMenuInflater();
		inflater.inflate(R.menu.note_video, menu);
		return true;
	}

	@Override
	public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
		return false;
	}

	@Override
	public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
		switch (item.getItemId()) {
		
		case R.id.menuSoundPlay: {
			//launch VideoActivity to play fullscreen video
			Intent launchVideo = new Intent(noteActivity.getApplicationContext(), VideoViewerActivity.class);
			launchVideo.putExtra("videoUri", videoBuilder.getPath());
			noteActivity.startActivity(launchVideo);
			return true;
		}

		case R.id.menuUnlockView: { 
			UpdateView.move(video, noteActivity);
			noteActivity.clickie("Video unlocked and moveable.");
			return true;
		}
		
		case R.id.menuDeleteView: {
			UpdateView.deleteView(videoBuilder.getEntry(), noteActivity, video);
			mode.finish();
			videoBuilder = null;
			return true;
		}
			default:
				return false;
		}
	}

	@Override
	public void onDestroyActionMode(ActionMode mode) {
		if (videoBuilder != null){
			video.setOnTouchListener(null);
			UpdateView.setXY(videoBuilder.getEntry(), noteActivity, video);
		}
	}
}
