package com.comp490.studybuddy.note;

import android.app.AlertDialog;
import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import android.view.ActionMode;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.MotionEvent;
import android.view.View;
import android.view.View.OnTouchListener;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.RelativeLayout;

import com.comp490.studybuddy.R;

/* Generated by VideoBuilder onLongClick of a Video ImageButton. Provides a 
 * menu of options, including deletion of view (not the file) and also 
 * plays video fullscreen with VideoViewerActivity
 */
public class VideoMenu implements ActionMode.Callback {
	private NoteActivity noteActivity;
	private VideoBuilder videoBuilder;
	private static final String LOG_TAG = "Video Menu Callback";
	private int xDelta;
	private int yDelta;
	ImageButton video;
	OnTouchListener listen = null;

	// Video Contextual Action Mode

	public VideoMenu(NoteActivity noteActivity, VideoBuilder videoBuilder) {
		this.noteActivity = noteActivity;
		this.videoBuilder = videoBuilder;
		video = (ImageButton) noteActivity.findViewById(videoBuilder.getID());
	}

	@Override
	public boolean onCreateActionMode(ActionMode mode, Menu menu) {
		MenuInflater inflater = mode.getMenuInflater();
		inflater.inflate(R.menu.note_video, menu);
		return true;
	}

	@Override
	public boolean onPrepareActionMode(ActionMode mode, Menu menu) {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
		// TODO Auto-generated method stub
		switch (item.getItemId()) {
		
		case R.id.menuSoundPlay: {
			//launch VideoActivity to play fullscreen video
			Intent launchVideo = new Intent(noteActivity.getApplicationContext(), VideoViewerActivity.class);
			launchVideo.putExtra("videoUri", videoBuilder.data.toString());
			noteActivity.startActivity(launchVideo);
			return true;
		}

		case R.id.menuUnlockView: { 
			allowViewMovement();
			noteActivity.clickie("Video icon unlocked.");
			return true;
		}
		
		case R.id.menuDeleteView: {
			AlertDialog.Builder builder = new AlertDialog.Builder(noteActivity);
			builder.setMessage("Delete Item?");
			builder.setPositiveButton("Yes",
					new DialogInterface.OnClickListener() {
						@Override
						public void onClick(DialogInterface dialog, int id) {
							try { // clicked yes
								((ViewGroup) video.getParent())
										.removeView(video);
								videoBuilder.deleteObject();
								videoBuilder = null;
							} catch (Exception e1) {
								Log.e(LOG_TAG, "Delete of VideoView failed");
							}
						}
					});
			builder.setNegativeButton("Cancel",
					new DialogInterface.OnClickListener() {
						@Override
						public void onClick(DialogInterface dialog, int id) {
							dialog.cancel();
						}
					});
			AlertDialog dialog = builder.create();
			dialog.show();
			mode.finish();
			return true;
		}
		default:
			return false;
		}
	}

	@Override
	public void onDestroyActionMode(ActionMode mode) {
		video.setOnTouchListener(null);
		noteActivity.clickie("Video icon position locked.");
		//TO DO: need to update location X, Y in entry
	}

	public void allowViewMovement() {

		final ViewGroup parent = (ViewGroup) noteActivity
				.findViewById(R.id.note_layout);

		listen = new OnTouchListener() {
			@Override
			public boolean onTouch(View view, MotionEvent event) {
				final int X = (int) event.getRawX();
				final int Y = (int) event.getRawY();

				switch (event.getAction() & MotionEvent.ACTION_MASK) {
				case MotionEvent.ACTION_DOWN:
					RelativeLayout.LayoutParams lParams = (RelativeLayout.LayoutParams) view
							.getLayoutParams();
					xDelta = X - lParams.leftMargin;
					yDelta = Y - lParams.topMargin;
					break;
				case MotionEvent.ACTION_UP:
					break;
				case MotionEvent.ACTION_POINTER_DOWN:
					break;
				case MotionEvent.ACTION_POINTER_UP:
					break;
				case MotionEvent.ACTION_MOVE:
					RelativeLayout.LayoutParams layoutParams = (RelativeLayout.LayoutParams) view
							.getLayoutParams();

					if (X - xDelta < 0)
						layoutParams.leftMargin = 0;
					else
						layoutParams.leftMargin = X - xDelta;
					if (Y - yDelta < 0)
						layoutParams.topMargin = 0;
					else
						layoutParams.topMargin = Y - yDelta;
					
	            layoutParams.bottomMargin = -250;
	            layoutParams.rightMargin = -250; 

					view.setLayoutParams(layoutParams);
					break;
				}
				parent.invalidate();
				return true;
			}
		};

		video.setOnTouchListener(listen);
	}

}
